### PR TITLE
Reexport proto create since usage of rust-mesos depends on it.

### PR DESCRIPTION
**Pull request by kolloch**

### CODE REVIEW

**Comment by bonifaido** [comment]
Thank you Peter!
I wonder how this didn't blow up in the example code.

**Comment by kolloch** [comment]
I am also not sure if what I did was the idiomatic rust way.

In your example you have all your dependencies at your disposition. You specify "extern crate proto".

In theory, one could also import your "proto" in any crates using rust-mesos as a separate dependency. Since the objects are really part of the API and the mesos crate is not usable without the proto objects, I think that I would include it (as I did).

It would probably make sense to update the example and remove "extern crate proto" and use the "mesos::proto" path to refer to the interface object.

**Comment by bonifaido** [comment]
Yes, the official Java binding ships with baked in protobuf bindings as well. I think we should do the same, I will refine the example.

**Comment by bonifaido** [comment]
I have re-exported the public messages in a hopefully more idiomatic way, please check it out. :)
Commit: 33ec080cbf9a37829d821bc5d361129caea3409c

**Pull request merged**
